// Options the user could type in
const prompts = [
    ["how are you"],
    ["2023","2023 batch","2023 fees","fees 2023"],
    ["hi","hii","hai","haii","hello","good morning", "hey", "good afternoon"],
    ["cse support","support","contact support","contact","cse contact","more details","more detail","more","contact address"],
    ["cse","computer science and engineering"],
    ["fees details","fees"],
    ["dress code","dres code","dress","cse dress code","cse dress","dress code for cse","dress rules","rules for wearing dress","student apperance"],
    ["cse department","cse dept","cse started year"],
    ["number of bus","no of bus","bus","how many bus","total number of bus","total bus","total number bus"],
    ["cse hod","hod"],
    ["bus facility","bus route","bus route","bus area","bus areas","area of bus"],
    ["staff","staff details","staff detail"],
    ["ksrce staff"],
    ["ksr","about ksr","tell about ksr","tell me about ksr"],
    ["research","college research","researchs"],
    ["placement","placement details","placed student","student palced","placement list"],
    ["counselling code","code"],
    ["what", "why", "how", "where", "when"],
    ["no","not sure","maybe","no thanks"],
    // ["tell me about ksrce","about ksrce",],
    ["haha","ha","lol","hehe","funny","joke"],
    ["bye","thank you","see you later","byee","bye bye"],
    ["hostel menu","hostel food","food list","list of food","food"],
    ["monday","monday food","food monday","monday food list"],
    ["tuesday","tuesday food","food tuesday","tuesday food list"],
    ["wednesday","wednesday food","food wednesday","wednesday food list"],
    ["thursday","thursday food","food thursday","thursday food list"],
    ["friday","friday food","food friday","friday food list"],
    ["saturday","saturday food","food saturday","saturday food list"],
    ["sunday","sunday food","food sunday","sunday food list"],
    ["food court","canteen","shop","department store","stationary"],
    ["location","locat","place","area","airport","railwaystation"],
    ["alumini","alumin","college alumini","college alumin"],
    ["hostel rules","rules hostel","rules for hostel","hostel rule"],
    ["college time","college timing","college work time","college work timing","college working time","time","timing","college open time","college opening time","college closing time","college close time","work time"],
    ["college working days","college open","working days","work day","work days","college work days","college work day"]
  ]
  // Possible responses, in corresponding order
  const replies = [
    ["I'm Fine.. How can I help you?"],
    ["current fees for cse 2023, any queries type more  automatically given contact number"],
    ["Hii Heartily <b>Welcome to KSRCE and CSE Department</b>"],
    ["<b>Dr.A.Rajiv Kannan, M.E., Ph.D., MISTE., MCSI.,Head of the Department</b>,Department of Computer Science and Engineering K.S.R College of Engineering,Tiruchengode - 637215.<b>Email: hodcse@ksrce.ac.in Mobile: +(91) 9787866666</b>"],
    ["Department of CSE was started in the year 2001 initially with B.E Programme. With the increasing demand in Computer Science and Engineering, M.E programme was started in the year 2007. The department is recognized to offer the research programme for Ph.D. " ],
    ["CSE fees approximately 1.5L anything else contact-9787866666 , Mail id-hodcse@ksrce.ac.in"],
    ["Formal shirt and Formal pant with Proper shoe"],
    ["The Department of CSE  was started under Aarthi Educational and Charitable Trust in the year 2001 by our Founder & Chairman Dr. K. S. Rangasamy MJF., "],
    ["The K.S.R. Educational Institutions operates  more than 167 buses"],
    ["Dr.A.Rajiv Kannan is HOD of CSE department"],
    ["Nearly 100 KM  radius from the various districts - Attur, Kolathur, Vaazhapadi, Satthiyamangalam, Namakkal, Erode, Salem, Karur and Tirupur. This Bus Facilities are provided to all Students, Faculty members and Staffs of K.S.R. Educational Institutions."],
    ["There are more than 25 teaching Faculty, 4 Non-teaching Faculty in CSE Department"],
    ["More than 150 teaching faculty are working in KSRCE"],
    ["Welcome to KSREI,There are 19 INSTUTIONS in our Campus,3 ENGINEERING COLLEGES,3 Schools,WOMEN College,etc.."],
    ["<span class='messagespan'>visit our ksrcecse official website LINK:</span><a href='https://ksrcecse.onrender.com/src/html/research.html'>Click Me</a>"],
    ["<span class='messagespan'>visit our ksrcecse official website LINK:</span><a href='https://ksrcecse.onrender.com'>Click Me</a>"],
    ["TNEA Counselling Code= <b>2613</b>"],
    ["Great question"],
    ["That's ok","I understand","What do you want to talk about?"],
    // [""],
    ["Haha!","Good one!"],
    ["ThankYou For Visiting..."],
    ["Please choose and type here..<b><br><button onclick=\"foodcall('monday')\">1.MONDAY</button><br>2.TUESDAY<br>3.WEDNESDAY<br>4.THURSDAY<br>5.FRIDAY<br>6.SATURDAY<br>7.SUNDAY</b>"],
    ["<b>Monday</b>-->(<b>Breakfast</b>:Bread jam,omelet,upma)<br>(<b>Lunch</b>:rice,pulikolambu,carrotporiyal),<br>(<b>Dinner</b>:Idly or Dosai)"],
    ["<b>Tuesday</b>-->(<b>Breakfast</b>:Noodles+Onnion Dosai)<br>(<b>Lunch</b>:rice,sambar(egg+chips)),<br>(<b>Dinner</b>:Dosai)"],
    ["<b>Wednesday</b>-->(<b>Breakfast</b>:Ven Pongal+Vadai)<br>(<b>Lunch</b>:rice + chappathi,pachipaiyurKolambu,gabbage poriyal),<br>(<b>Dinner</b>:chapatti chicken Gravy or Briyani))"],
    ["<b>Thursday</b>-->(<b>Breakfast</b>:Idly)<br>(<b>Lunch</b>:rice,pulikolambu,beetroot poriyal),<br>(<b>Dinner</b>:poori)"],
    ["<b>Friday</b>-->(<b>Breakfast</b>:Dosai + kesari)<br>(<b>Lunch</b>:rice,variety rice,Sambar,potato poriyal),<br>(<b>Dinner</b>:chapatti,channa Masala)"],
    ["<b>Saturday</b>-->(<b>Breakfast</b>:Kothumi upma ,egg noodles,veg noodles)<br>(<b>Lunch</b>:rice,pulikolambu,poriyal),<br>(<b>Dinner</b>:Naan or parotta)"],
    ["<b>Sunday</b>-->(<b>Breakfast</b>:Roast)<br>(<b>Lunch</b>:rice,chickenkolambu,poriyal),<br>(<b>Dinner</b>:variety rice)"],
    ["In our campus there are 5 food courts,department store,Textile shop etc..."],
    ["K.S.R. College of Engineering, Tiruchengode is situated at K.S.R. Kalvi Nagar, Tiruchengode, Tamil Nadu. The nearest railway station is Erode Junction, which is about 14 KM away from the college and the nearest airport is Salem Airport, which is about 58 KM away from the college."],
    ["In the department of CSE ,there are more than 2500 Alumini"],
    ["Morning out time:9:00AM<br>evening in time:4:00PM to 7:00PM<br>After 7:00PM ,students are not allowed inside the Hostel"],
    ["9:00AM-to-4:00PM"],
    ["Working days Monday-Saturday<br>Every sunday will be declared as a Holiday"]
  ]
  // Random for any other user input
  const alternative = [
    "Try again",
    "I'm not listening...Try again",
    "I don't understand :/"
  ]
  // Whatever else you want :)
  const coronavirus = ["Please stay home", "Wear a mask", "Fortunately, I don't have COVID", "These are uncertain times"]
  const developers = ["Developed by Batch(2020-2024) JEYANDHANN, DEEPAK KUMAR, DHANUSH, GOPIKANNAN, GOKULSHARMA, HARIHARAN"]
